oVirt/ost-images

build.sh
FIPS should work now on el9stream.
=> el9stream: Re-enable FIPS

el8stream-provision-host.sh.in, el9stream-provision-host.sh.in
This reverts acbc2ddf7065fd877d3e52a06ed094a531d1e0ad
=> el8stream-provision-host.sh.in still needs the workaround

build.sh
The problem is fixed in u/s [1], but the change didn't land in el9stream
yet.
[1] https://gitlab.com/redhat/centos-stream/rpms/python3.9/-/merge_requests/21
This reverts commit 888f613252b46e28cc35df573100f05e66767258.
=> Revert "el9stream: Re-enable FIPS"

el8stream-provision-host.sh.in, el9stream-provision-host.sh.in
- el8stream-provision-host.sh.in still needs the workaround
- el8stream-provision-host.sh.in: unify the dnf copr enable command
=> copr again

el8stream-provision-he.sh.in
The appliance is now published by a github action, to a different place,
and ovirt-release correctly points there. So use that instead of
pointing to a specific repo.
Change-Id: I182a04e7e2598ddde8a78989cef422ff7de9d842
Signed-off-by: Yedidyah Bar David <didi@redhat.com>
=> HE: Install the appliance from default repos

rhel8-provision-engine.sh.in.in
Adding tr-ocp-installer package.
This is a dummy package that will have
the real openshift-install bin just after upgrade.
The openshift-install bin is built with the related patch in
terraform-provider-ovirt repo and its purpose is to check if changes
suggested by the patch are fully compatible with OCP.
In its initial form the package contains a shell script
named openshift-install that prints an error and exists.
Signed-off-by: emesika <emesika@redhat.com>
=> Adding tr-ocp-installer package

makefiles/engine-installed.mk, makefiles/he-installed.mk
Entour the command with quotes.
=> Fix broken arguments passed to `virt-customize`

build.sh
Security profiles don't work properly on these distros.
We should use them only in rhel8.
=> Don't use security profiles on el[89]stream and node

build.sh
let's download just the one distro that's being built instead of all of
them. When building within a throw-awway container we only need the one.
=> refactor CentOS images caching

.github/workflows/build.yml
it's handy in case of failures
=> github: save console log to GH artifacts

node.ks.in
=> Drop auth in node/rhvh kickstart

build.sh, configure.ac, makefiles/vars.mk, ost-images.spec.in
This patch adds '--with-distro' option to configure the desired
distro at the './configure' invocation level. With this change,
once a build is configured to use a specific distro, one does
not need to pass the 'DISTRO' var again to subsequent 'make'
commands (i.e. 'make DISTRO=mydistro clean').
=> autoconf: Add '--with-distro' option

Makefile.am, build.sh, makefiles/base.mk, makefiles/preinstalled-base.mk, makefiles/vars.mk, ost-images.spec.in
base: Remove support for builds based on top of existing base
Until now we had the option to use an existing base image
(one installed along 'ost-images-DISTRO-base' RPM package)
as the foundation for all the other images. This made sense
when we were building CentOS 8 images with 'upgrade' layer
in between, but now we're working with rolling release distros
or nightly repos. Let's remove the logic that allowed that.
=> base: Remove support for builds based on top of existing base

provision-base.sh
The chronyd server check requires manual
remmediation.
Signed-off-by: Ales Musil <amusil@redhat.com>
=> base: Ignore chronyd server check rule

el9stream.ks.in
COPR is using SHA-1 when signing packages. SHA-1 is not supported
in el9stream's default crypto policy. Until [1] is resolved
we need to use 'LEGACY' crypto policy to work with el9stream.
[1] https://pagure.io/copr/copr/issue/2106
=> el9stream: Use 'LEGACY' crypto policy

provision-base.sh, rhel8.ks.in
The fapolicyd version needed by ovirt-engine (>=1.1),
should be available.
Signed-off-by: Ales Musil <amusil@redhat.com>
=> Enable fapolicyd again

makefiles/vars.mk
glance.ovirt.org has proven itself to be unreliable
and currently fails with 500 server error. Let's move
the cirros image to a different server.
=> cirros: Move image to templates.ovirt.org

provision-base.sh
Those rules are not easily applicable for HE, let's just skip
them.
Signed-off-by: Ales Musil <amusil@redhat.com>
=> base: Exclude grub login rules from scap datastream

configs/rhel8/rhel8.ks.in, provision-base.sh
In order to ensure that only eth0 will always be default
route create connection files. The "never-default=True" will
be applied to all interfaces except eth0.
Signed-off-by: Ales Musil <amusil@redhat.com>
=> base: Create connection files

.github/workflows/selenium.yml
This patch introduces a workflow that pulls the latest Selenium
images from docker.io and publishes them on quay.io.
=> Workflow for updating Selenium images on quay.io

configs/storage/setup_selenium_grid.sh
With [1] merged we should get fresh Selenium images every month/on
demand.
[1] https://github.com/oVirt/ost-images/pull/49
=> Use latest Selenium images in images

configs/rhel8/rhel8-provision-engine.sh.in
In https://github.com/oVirt/go-ovirt-client/pull/200 we renamed
tr-suite-master and dropped terraform from testing. From now on we only
test with go-ovirt-client-tests. And a dummy rpm is not really needed
anyway
=> drop tr-ocp-installer

configs/el8stream/el8stream-provision-host.sh.in, configs/el9stream/el9stream.ks.in
it was out workaround to set cryptopolicy to LEGACY. That issue is fixed
now and we can sue defaults.
=> fix FIPS on el9

configs/el9stream/el9stream.ks.in
we got it as a transient dependency on el8 but not anymore on el9
=> el9stream: add uuid package

configs/rhel8/rhel8.ks.in
DISA STIG openscap report is complaining about smart cards not being
enabled in relevant configuration files. Let's try using the 'sssd'
authselect profile with smart cards enabled.
=> authselect: Switch profile to 'sssd' with smart cards

provision-base.sh
now openscap is also failing on smartcards not being enabled, since sssd
configuration is manual already we can as well just skip this rule too.
=> rhel8: extend openscap SSSD skip

configs/el9stream/el9stream-provision-engine.sh.in
All required dependencies for CS9 for ovirt-engine should be built
successfully on CBS
Signed-off-by: Martin Perina <mperina@redhat.com>
=> Remove EL8 dependencies hack

configs/node/node.ks.in
we use "uuid" in provision-base.sh, but on el9 it needs to be installed.
It was added in ae748771924a4f22e8f1f6357d45e5e4715a504d to regular
hosts but it's missing in node too.
=> el9node: add uuid package

configs/el8stream/el8stream.ks.in
on storage it's been missing as well, let's be expicit everywhere and
require uuid package to be present
=> el8stream,storage: add uuid package too

configs/storage/setup_selenium_grid.sh
The 4.4.0 Selenium version is more unstable than 4.0.0.
=> selenium: Go back to 4.0.0

.github/workflows/selenium.yml, configs/storage/setup_selenium_grid.sh
In this PR we do an overhaul of things around Selenium:
- we remove the scheduled container build for now. We can consider
bringing it here again if we manage to stabilize UI tests.
- we add a parameter to specify which Selenium version to use.
Until now we were always pulling 'latest' and pushing to our own quay
repo as 'latest'. With the change we pull the version specified by
'selenium_version' parameter and push to our own quay repo as
'latest'. This way, the provisioning script and OST side can always
use 'latest' and we never have to sync those two again.
- the video image always uses 'latest' tag
- we update the names of pulled/push container names to reflect the
reality
=> Update selenium workflow and provisioning script

makefiles/he-installed.mk
'sysstat' on el9stream requires additional packages to be available.
This doesn't break el8stream.
=> he: Add missing packages for el9stream

configs/rhel8/rhel8-provision-engine.sh.in, configs/rhel8/rhel8-provision-he.sh.in, configs/rhel8/rhel8-provision-host.sh.in
We started to use a server with self-signed certificates for
ovirt-engine nightly builds. Ignore it using sslverify=false.
=> rhel8: self-signed server for ovirt-engine nightly

build.sh
due to the way jenkins jobs are chained there's a timing issue with
archiving the results, if we run a new build right after the previous
one the artifacts may not have been copied just yet. It's idiotic, but
let's just wait a little...2 minutes ought to be enough for anyone.
=> jenkins timing issue

configs/el8stream/el8stream-provision-host.sh.in, configs/node/node.ks.in, configs/rhel8/rhel8-provision-host.sh.in
Problems with nested VMs' firmware are hard to debug. A dump of firmware
log is very helpful with that, so let's have it on by default in OST.
=> Add vdsm-hook-log-firmware hook to hosts

provision-base.sh
A new rule has been introduced to openscap recently that breaks rhel8
runs. It seems to restrictive for our purposes, so let's ignore it.
=> rhel8: Ignore new fapolicyd rule

configs/el8stream/el8stream.ks.in, configs/el9stream/el9stream.ks.in, configs/rhel8/rhel8.ks.in, makefiles/vars.mk
'el8stream' builds are complaining about disk space, so let's bump it.
=> base: Bump disk and /var partition size

build.sh, configs/alma9/alma9-provision-he.sh.in, configs/alma9/alma9-provision-host.sh.in, configs/alma9/alma9.ks.in, configs/alma9/build.env, configs/el8stream/el8stream-provision-engine.sh.in, configs/el8stream/el8stream-provision-host.sh.in
This patch provides initial config for AlmaLinux 9.
Similar to CentOS Stream 9, engine build is turned off at the moment.
On AlmaLinux 9 'VERSION_ID' takes a value of '9.0', so we need to trim
the string to match the COPR chroot name.
=> Introducing AlmaLinux 9 images

configs/el9stream/el9stream-provision-engine.sh.in, makefiles/engine-installed.mk
By default files in /var/tmp are removed if they haven't been accessed for 30 days. So, if you run ost with images older then those 30 days the cirros image is cleaned up automatically. To mitigate this we move the image to /usr/share/ovirt-system-tests.
=> ost-images: move cirros.img
